"""Update database model again

Revision ID: 2302a8a67b25
Revises: e2f49e525c54
Create Date: 2023-06-24 20:32:33.232672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2302a8a67b25'
down_revision = 'e2f49e525c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_column('code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.TEXT(length=10), nullable=False))

    # ### end Alembic commands ###
